#!/bin/bash 
sudo apt update -y

sudo apt upgrade -y

sudo apt install -y apache2 apache2-utils

sudo systemctl enable apache2

sudo iptables -I INPUT -p tcp --dport 80 -j ACCEPT

sudo ufw allow http

sudo chown www-data:www-data /var/www/html/ -R

echo "ServerName localhost" | sudo tee -a /etc/apache2/conf-available/servername.conf



sudo apt install mariadb-server mariadb-client -y

sudo systemctl start mariadb

sudo systemctl enable mariadb

sudo mysql_secure_installation

sudo apt install php7.4 php7.4-fpm php7.4-mysql php-common php7.4-cli php7.4-common php7.4-json php7.4-opcache php7.4-readline php7.4-mbstring php7.4-xml php7.4-gd php7.4-curl -y

sudo systemctl start php7.4-fpm

sudo systemctl enable php7.4-fpm

sudo a2dismod php7.4
sudo apt install php7.4-fpm
sudo a2enmod proxy_fcgi setenvif
sudo a2enconf php7.4-fpm
sudo systemctl restart apache2


wget https://download.nextcloud.com/server/releases/nextcloud-22.2.3.zip
sudo apt install unzip
sudo unzip nextcloud-22.2.3.zip -d /var/www/
sudo chown www-data:www-data /var/www/nextcloud/ -R

sudo mysql -e "CREATE DATABASE IF NOT EXISTS nextcloud"

sudo mysql -e "CREATE USER IF NOT EXISTS 'nextclouduser'@'localhost' IDENTIFIED BY 'Password01'"

sudo mysql -e "GRANT ALL PRIVILEGES ON nextcloud.* to 'nextclouduser'@'localhost'"
 
sudo mysql -e "FLUSH PRIVILEGES"



read -p "Enter IP:" Ip
sudo sed -i "s/$Ip/*/" /var/www/nextcloud/config/config.php
sudo rm -r /etc/apache2/sites-available/000-default.conf
  echo "<VirtualHost *:80>
          DocumentRoot \"/var/www/nextcloud\"
          ServerName $Ip

          ErrorLog ${APACHE_LOG_DIR}/nextcloud.error
          CustomLog ${APACHE_LOG_DIR}/nextcloud.access combined

          <Directory /var/www/nextcloud/>
              Require all granted
              Options FollowSymlinks MultiViews
              AllowOverride All

             <IfModule mod_dav.c>
                 Dav off
             </IfModule>

          SetEnv HOME /var/www/nextcloud
          SetEnv HTTP_HOME /var/www/nextcloud
          Satisfy Any

         </Directory>

  </VirtualHost>" | sudo tee -a /etc/apache2/sites-available/nextcloud.conf

sudo a2ensite nextcloud.conf
sudo a2enmod rewrite headers env dir mime setenvif ssl
sudo apache2ctl -t
sudo systemctl restart apache2
sudo apt install imagemagick php-imagick libapache2-mod-php7.4 php7.4-common php7.4-mysql php7.4-fpm php7.4-gd php7.4-json php7.4-curl php7.4-zip php7.4-xml php7.4-mbstring php7.4-bz2 php7.4-intl php7.4-bcmath php7.4-gmp
sudo apt install php-ldap -y
sudo systemctl reload apache2

sudo mkdir /var/www/nextcloud-data
sudo chown www-data:www-data /var/www/nextcloud-data -R
sudo sed -i 's/memory_limit = 128M/memory_limit = 512M/g' /etc/php/7.4/apache2/php.ini
sudo systemctl reload php7.4-fpm

